INSERT INTO FOOD_CATEGORY (CATEGORY_NAME,IMAGE_FILE_NAME)
VALUES ('Specialty Pizza','specialty.png');
INSERT INTO FOOD_CATEGORY (CATEGORY_NAME,IMAGE_FILE_NAME)
VALUES ('Breads & Oven-Baked Dips','breadandovenbakeddips.png');
INSERT INTO FOOD_CATEGORY (CATEGORY_NAME,IMAGE_FILE_NAME)
VALUES ('Chicken','chicken.png');
INSERT INTO FOOD_CATEGORY (CATEGORY_NAME,IMAGE_FILE_NAME)
VALUES ('Desserts','dessert.png');
INSERT INTO FOOD_CATEGORY (CATEGORY_NAME,IMAGE_FILE_NAME)
VALUES ('Pasta','pasta.png');
INSERT INTO FOOD_CATEGORY (CATEGORY_NAME,IMAGE_FILE_NAME)
VALUES ('Oven Baked Sandwiches','sandwiches.png');
INSERT INTO FOOD_CATEGORY (CATEGORY_NAME,IMAGE_FILE_NAME)
VALUES ('Salads','salads.png');
INSERT INTO FOOD_CATEGORY (CATEGORY_NAME,IMAGE_FILE_NAME)
VALUES ('Drinks','drinks.png');
INSERT INTO FOOD_CATEGORY (CATEGORY_NAME,IMAGE_FILE_NAME)
VALUES ('Extras','extras.png');
COMMIT;