INSERT INTO FOOD_CATEGORY (CATEGORY_ID,CATEGORY_NAME,IMAGE_FILE_NAME)
VALUES (1,'Specialty Pizza','specialty.png');
INSERT INTO FOOD_CATEGORY (CATEGORY_ID,CATEGORY_NAME,IMAGE_FILE_NAME)
VALUES (2,'Breads & Oven-Baked Dips','breadandovenbakeddips.png');
INSERT INTO FOOD_CATEGORY (CATEGORY_ID,CATEGORY_NAME,IMAGE_FILE_NAME)
VALUES (3,'Chicken','chicken.png');
INSERT INTO FOOD_CATEGORY (CATEGORY_ID,CATEGORY_NAME,IMAGE_FILE_NAME)
VALUES (4,'Desserts','dessert.png');
INSERT INTO FOOD_CATEGORY (CATEGORY_ID,CATEGORY_NAME,IMAGE_FILE_NAME)
VALUES (5,'Pasta','pasta.png');
INSERT INTO FOOD_CATEGORY (CATEGORY_ID,CATEGORY_NAME,IMAGE_FILE_NAME)
VALUES (6,'Oven Baked Sandwiches','sandwiches.png');
INSERT INTO FOOD_CATEGORY (CATEGORY_ID,CATEGORY_NAME,IMAGE_FILE_NAME)
VALUES (7,'Salads','salads.png');
INSERT INTO FOOD_CATEGORY (CATEGORY_ID,CATEGORY_NAME,IMAGE_FILE_NAME)
VALUES (8,'Drinks','drinks.png');
INSERT INTO FOOD_CATEGORY (CATEGORY_ID,CATEGORY_NAME,IMAGE_FILE_NAME)
VALUES (9,'Extras','extras.png');
COMMIT;