INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (1,'extravanganZZa',18.49,1,"extravanganZZa.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (2,'FiveCheese',8.99,2,"FiveCheese.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (3,'CripsyBaconTomato',7.99,3,"CripsyBaconTomato.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (4,'CinnamonTwists',5.99,4,"CinnamonTwists.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (5,'ChickenAlfredo',7.99,5,"ChickenAlfredo.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (6,'Buffalo_Chicken',7.99,6,"Buffalo_Chicken.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (7,'Classic_Garden',7.99,7,"Classic_Garden.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (8,'Coke',3.49,8,"Coke.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (9,'ParmesanCheesePackets',0.00,9,"ParmesanCheesePackets.png");