USE RESTAURANT;
create table IF NOT EXISTS DISH(
DISH_ID int not null, 
DISH_NAME char(75) NOT NULL, 
DISH_PRICE DECIMAL(5,2) DEFAULT 11.99,
CATEGORY_ID int not null,
DISH_IMG char(80) NOT NULL, 
primary key (DISH_ID),
CONSTRAINT FK_CATEGORY_ID FOREIGN KEY (CATEGORY_ID)
REFERENCES FOOD_CATEGORY(CATEGORY_ID)
);