USE RESTAURANT;
create table IF NOT EXISTS DISH(
DISH_ID int not null, 
DISH_NAME char(40) NOT NULL, 
DISH_PRICE DECIMAL(5,2) NOT NULL,
CATEGORY_ID int not null, 
primary key (DISH_ID),
FOREIGN KEY (CATEGORY_ID) REFERENCES FOOD_CATEGORY(CATEGORY_ID)
);