INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (1,'extravanganZZa',18.49,1,"extravanganZZa.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (2,'MeatZZa',18.49,1,"MeatZZa.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (3,'Philly Cheese Steak',18.49,1,"Philly_Cheese_Steak.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (4,'Pacific Veggie',18.49,1,"Pacific_Veggie.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (5,'Honolulu Hawaiian',18.49,1,"Honolulu_Hawaiian.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (6,'Deluxe',18.49,1,"Deluxe.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (7,'Cali Chicken Bacon Ranch',18.49,1,"Cali_Chicken_Bacon_Ranch.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (8,'Buffalo Chicken',18.49,1,"Buffalo_Chicken.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (9,'Ultimate Pepperoni',18.49,1,"Ultimate_Pepperoni.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (10,'Memphis BBQ Chicken',18.49,1,"Memphis_BBQ_Chicken.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (11,'Wisconsin 6 Cheese',18.49,1,"Wisconsin_6_Cheese.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (12,'Spinach & Feta',18.49,1,"Spinach_&_Feta.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (13,'Five Cheese Dip & Bread Twists',8.99,2,"Five_Cheese_Dip_&_Bread_Twists.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (14,'Cheesy Marinara',8.99,2,"Cheesy_Marinara_Dip_&_Bread_Twists.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (15,'Parmesan Bread Twists',8.99,2,"Parmesan_Bread_Twists.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (16,'Garlic Bread Twists',8.99,2,"Garlic_Bread_Twists.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (17,'Stuffed Cheesy Bread',8.99,2,"Stuffed_Cheesy_Bread.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (18,'Stuffed Cheesy Bread with Spinach & Feta',8.99,2,"Stuffed_Cheesy_Bread_with_Spinach_&_Feta.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (19,'Stuffed Cheesy Bread with Bacon & Jalapeno',8.99,2,"Stuffed_Cheesy_Bread_with_Bacon_&_Jalapeno.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (20,'Parmesan Bread Bites',8.99,2,"Parmesan_Bread_Bites.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (21,'Cinnamon Bread Twists',8.99,2,"Cinnamon_Bread_Twists.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (22,'Cheesy Marinara Dip',8.99,2,"Cheesy_Marinara_Dip.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_PRICE,CATEGORY_ID,DISH_IMG)
VALUES (23,'Five Cheese Dip',8.99,2,"Five_Cheese_Dip.png");
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (24,'Specialty Chicken - Crispy Bacon & Tomato',3,'S_SCCBT.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (25,'Specialty Chicken - Classic Hot Buffalo',3,'S_SCCHB.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (26,'Specialty Chicken - Spicy Jalapeno - Pineapple',3,'S_SCSJP.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (27,'Specialty Chicken - Sweet BBQ Bacon',3,'S_SCSBBQ.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (28,'Hot Buffalo Wings',3,'S_HOTWINGS.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (29,'Honey BBQ Wings',3,'S_BBQW.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (30,'Plain Wings',3,'S_PLNWINGS.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (31,'Sweet Mango Habanero Wings',3,'S_SMANG.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (32,'Garlic Parmesan Wings',3,'S_GPRMWING.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (33,'Boneless Chicken',3,'S_BONELESS.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (34,'Cinnamon Bread Twists',4,'F_CINNAT.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (35,'Dominos Marbled Cookie Brownie™',4,'F_MRBRWNE.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (36,'Chocolate Lava Crunch Cakes',4,'F_LAVA.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (37,'Chicken Alfredo',5,'S_ALFR.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (38,'Italian Sausage Marinara',5,'S_MARIN.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (39,'Chicken Carbonara',5,'S_CARB.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (40,'Pasta Primavera',5,'S_PRIM.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (41,'Build Your Own Pasta',5,'S_BUILD.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (42,'Buffalo Chicken',6,'S_BUFC.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (43,'Chicken Habanero',6,'S_CHHB.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (44,'Mediterranean Veggie',6,'S_MEDV.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (45,'Philly Cheese Steak',6,'S_PHIL.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (46,'Chicken Bacon Ranch',6,'S_CHIKK.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (47,'Italian',6,'S_ITAL.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (48,'Chicken Parm',6,'S_CHIKP.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (49,'Classic Garden',7,'F_GARDEN.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (50,'Chicken Caesar',7,'F_CCAESAR.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (51,'Coke®',8,'F_COKE.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (52,'Coca-Cola Zero Sugar',8,'F_ZERO.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (53,'Diet Coke®',8,'F_DIET.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (54,'Sprite®',8,'F_SPRITE.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (55,'Dasani® Bottle Water',8,'F_WATER.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (56,'Fanta® Orange',8,'F_ORAN.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (57,'Hot Buffalo Dipping Cup',9,'F_HOTCUP.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (58,'Sweet Mango Habanero Sauce',9,'F_SMHAB.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (59,'Honey BBQ Dipping Cup',9,'F_BBQC.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (60,'Ranch',9,'F_SIDRAN.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (61,'Blue Cheese',9,'F_Bd.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (62,'Garlic Dipping Sauce',9,'F_SIDGAR.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (63,'Icing Dipping Sauce',9,'F_SIDICE.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (64,'Marinara Dipping Sauce',9,'F_SIDMAR.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (65,'Caesar Dressing',9,'F_CAESAR.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (66,'Ranch Dressing',9,'F_RANCHPK.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (67,'St. Jude Donation',9,'F_STJUDE.jpg');
INSERT INTO DISH (DISH_ID,DISH_NAME,CATEGORY_ID,DISH_IMG) VALUES (68,'Balsamic',9,'F_BALVIN.jpg');
COMMIT;